server:
  port: 9192

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/Plantes_Medicinales
    password: Root123root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update